# Notas, pruebas, cÃ³mo hacer cosas...

In [2]:
# Importar librerias

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# display para mi merge

class display(object):
    """Display HTML representation of multiple objects"""
    template = """<div style="float: left; padding: 10px;">
    <p style='font-family:"Courier New", Courier, monospace'>{0}</p>{1}
    </div>"""
    def __init__(self, *args):
        self.args = args
        
    def _repr_html_(self):
        return '\n'.join(self.template.format(a, eval(a)._repr_html_())
                         for a in self.args)
    
    def __repr__(self):
        return '\n\n'.join(a + '\n' + repr(eval(a))
                           for a in self.args)

!pip install --upgrade pandas

Requirement already up-to-date: pandas in /opt/anaconda3/lib/python3.8/site-packages (1.1.3)
Requirement already satisfied, skipping upgrade: python-dateutil>=2.7.3 in /opt/anaconda3/lib/python3.8/site-packages (from pandas) (2.8.1)
Requirement already satisfied, skipping upgrade: pytz>=2017.2 in /opt/anaconda3/lib/python3.8/site-packages (from pandas) (2020.1)
Requirement already satisfied, skipping upgrade: numpy>=1.15.4 in /opt/anaconda3/lib/python3.8/site-packages (from pandas) (1.18.5)
Requirement already satisfied, skipping upgrade: six>=1.5 in /opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)

In [3]:
df = pd.read_csv('CP_national_en.csv', index_col = 0) # cargar datos, columna Country indice para evitrar uffef
df['Country'] = df.index.values       #Columna nueva con los valores del indice Country
df.index = list(range(len(df)))       #indice nuevo
first_col = df.pop('Country')       # saco la columna indice...
df.insert(0, 'Country', first_col, allow_duplicates = True)      # ...para insertarla a la cabeza

# ya tengo mi dataframe

df_original = df.copy()  # no trabajar con df original, dejar aqui guardado

df.drop(['Notes', 'More'], axis = 1, inplace = True)

# preparacion del dataframe para conseguir estructura deseada 

df = df.melt(id_vars=['Country', 'Indicator'], value_vars=['Latest year','Total', 'Men', 'Women'])
df.drop_duplicates(subset=['Country', 'Indicator', 'variable'], inplace=True)
df = df.pivot(index='Country', columns=['Indicator', 'variable'], values= 'value')
df.sort_values('Indicator', axis = 1, inplace = True)
orden = ['Latest year', 'Total', 'Men', 'Women']
df.reindex(orden, axis = 1, level = 1)

Indicator                 Average hourly labour cost per employee, local currency  \
variable                                                              Latest year
Country
Afghanistan                                                              NaN
Albania                                                                  NaN
Algeria                                                                  NaN
American Samoa                                                           NaN
Angola                                                                   NaN
...                                                                      ...
Viet Nam                                                                 NaN
Wallis and Futuna Islands                                                NaN
Yemen                                                                    NaN
Zambia                                                                   NaN
Zimbabwe                                                                 NaN

Indicator                                  \
variable                  Total Men Women
Country
Afghanistan                 NaN NaN   NaN
Albania                     NaN NaN   NaN
Algeria                     NaN NaN   NaN
American Samoa              NaN NaN   NaN
Angola                      NaN NaN   NaN
...                         ...  ..   ...
Viet Nam                    NaN NaN   NaN
Wallis and Futuna Islands   NaN NaN   NaN
Yemen                       NaN NaN   NaN
Zambia                      NaN NaN   NaN
Zimbabwe                    NaN NaN   NaN

Indicator                 Average monthly earnings of employees, local currency  \
variable                                                            Latest year
Country
Afghanistan                                                              NaN
Albania                                                               2019.0
Algeria                                                                  NaN
American Samoa                                                           NaN
Angola                                                                2011.0
...                                                                      ...
Viet Nam                                                              2019.0
Wallis and Futuna Islands                                                NaN
Yemen                                                                 2014.0
Zambia                                                                2017.0
Zimbabwe                                                              2019.0

Indicator                                                   \
variable                       Total        Men      Women
Country
Afghanistan                      NaN        NaN        NaN
Albania                      52380.0    54940.0    49411.0
Algeria                          NaN        NaN        NaN
American Samoa                   NaN        NaN        NaN
Angola                       55313.8    59827.4    44777.0
...                              ...        ...        ...
Viet Nam                   6656729.6  7000392.4  6205285.3
Wallis and Futuna Islands        NaN        NaN        NaN
Yemen                        66761.7    67557.0    49812.1
Zambia                        4016.6     3873.3     4368.8
Zimbabwe                       308.1      337.7      266.5

Indicator                 Average weekly hours actually worked per employed person  \
variable                                                               Latest year
Country
Afghanistan                                                           2017.0
Albania                                                               2019.0
Algeria                                                               2017.0
American Samoa                                                           NaN
Angola                                                                   NaN
...                                                                      ...
Viet Nam                                                              2019.0
Wallis and Futuna Islands                                                NaN
Yemen                                                                 2014.0
Zambia                                                                2018.0
Zimbabwe                                                              2019.0

Indicator                        ... Trade union density rate (%)        \
variable                  Total  ...                          Men Women
Country                          ...
Afghanistan                38.0  ...                          NaN   NaN
Albania                    41.2  ...                          NaN   NaN
Algeria                    43.7  ...                          NaN   NaN
American Samoa              NaN  ...                          NaN   NaN
Angola                      NaN  ...                          NaN   NaN
...                         ...  ...                          ...   ...
Viet Nam                   41.2  ...                          NaN   NaN
Wallis and Futuna Islands   NaN  ...                          NaN   NaN
Yemen                      40.0  ...                          NaN   NaN
Zambia                     40.2  ...                          NaN   NaN
Zimbabwe                   36.6  ...                          NaN   NaN

Indicator                 Unemployment rate (%)                    \
variable                            Latest year Total   Men Women
Country
Afghanistan                              2017.0  11.2  10.4  14.0
Albania                                  2019.0  11.5  11.6  11.3
Algeria                                  2017.0  13.6  10.8  26.2
American Samoa                           2010.0   9.2   NaN   NaN
Angola                                   2011.0   7.4   7.0   7.7
...                                         ...   ...   ...   ...
Viet Nam                                 2019.0   2.0   2.1   2.0
Wallis and Futuna Islands                2013.0  56.3   NaN   NaN
Yemen                                    2014.0  13.5  12.3  26.1
Zambia                                   2018.0  12.0  11.1  13.5
Zimbabwe                                 2019.0  16.9  16.0  17.9

Indicator                 Unemployment rate, youth (%)
variable                                   Latest year Total   Men Women
Country
Afghanistan                                     2017.0  17.6  16.3  21.4
Albania                                         2019.0  27.0  27.8  25.9
Algeria                                         2017.0  39.3  33.1  82.0
American Samoa                                     NaN   NaN   NaN   NaN
Angola                                          2011.0  16.7  16.8  16.6
...                                                ...   ...   ...   ...
Viet Nam                                        2019.0   6.9   6.9   6.9
Wallis and Futuna Islands                          NaN   NaN   NaN   NaN
Yemen                                           2014.0  24.5  23.5  34.6
Zambia                                          2018.0  26.0  24.7  27.6
Zimbabwe                                        2019.0  27.5  25.0  31.4

[209 rows x 88 columns]

In [ ]:
# Acceder a datos por fila
df[df.index == 'Spain']
# Acceder a nombres de columnas por nivel
df.columns.get_level_values(level = 0).unique()
# Cross section of dataframe with multindex
df.xs('Latest year', axis=1, level=1, drop_level=False)
#Convertir mis anos a int desde float. me da naans raros
df.xs('Latest year', axis=1, level=1, drop_level=True).astype('Int32')
#Modelo slicing. MUY IMPORTANTE, entender logica
df.loc[:,(['Average weekly hours actually worked per employed person', 
    'Population covered by at least one social protection benefit (%)'], ['Men','Women'])]
# codigo para pasar una columna al principio
first_col = paises_nvariables.pop('Country')     
paises_nvariables.insert(0, 'Country', first_col)  
paises_nvariables.index = list(range(len(paises_nvariables)))  #poner un indidce numerico ordenado


#numero y nombre de indicadores mercado laboral en todo el df
print(">>Numero indicadores del mercado laboral - todo el df:", df.Indicator.nunique())
print('\n')
print(">>Nombre indicadores del mercado laboral - todo el df: \n\n", df.Indicator.unique())

sns.displot(paises_nvariables, bins = paises_nvariables.nunique(), 
           kde = True);
plt.title('Conteo paises por variables con datos')

# Ver cuantas variables del mercado laboral hay recogidas por cada pais y meterlas en un Series

paises_nvariables = {}

for i in df['Country'].unique():

    paises_nvariables[i] = df[df['Country'] == i]['Indicator'].nunique()
    
paises_nvariables = pd.Series(paises_nvariables, name = 'paises_nvariables')

paises_nvariables = pd.DataFrame(paises_nvariables)

paises_nvariables.rename({"paises_nvariables" : 'Num Indicators'}, axis = 1, inplace = True)

paises_nvariables.sort_values('Num Indicators', ascending = False, inplace = True)

print(paises_nvariables.describe())

paises_nvariables['Country'] = paises_nvariables.index.values

sns.boxplot(data = paises_nvariables)

# Algunas manipulaciones

variables = df['Indicator'].unique()    # todos los nombres de variables que tenemos
variables

paro = df[df['Indicator'] == 'Unemployment rate (%)']    #df en la que solo sale el paro

paro['Latest year'].unique()

df[(df['Latest year'] == 2010) | (df['Latest year'] == 2011)]['Country'].unique()